### ISSUE TITLE
Is Javascript being benchmarked with an outdated version of NodeJS?

### ISSUE THREAD

**Issue by asparagii** [greensoftwarelab/Energy-Languages#20]
Javascript and Typescript benchmarks are using Node.js v7.9.0, which was released on 2017-04-11 and uses v8 version 5.5.372.43.
Is there a specific reason to use such an old Node release?
I think that using an outdated version of v8 might invalidate the benchmark results.

I think we should use the oldest maintainance LTS (Dubnium, v10.22.1, running v8 version 6.8.275.32), or maybe the active LTS (Erbium, v12.19.0, running v8 version 7.8.279.23)

**Comment by States** [comment]
The compiler versions used in this benchmark were based on a study executed in 2017 (https://sites.google.com/view/energy-efficiency-languages), which in turn used the compiler versions which were officially used in the Computer Language Benchmarks Game (https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html) at that time. 

Since, many compilers/interpreters have updated. Anyone is free to use our benchmarks and update accordingly. The settings currently present, are those of which were published however.

**Comment by asparagii** [comment]
I understand the reasoning, thank you
