### ISSUE TITLE
Update Chapel filename extensions

### ISSUE THREAD

**Issue by ben-albrecht** [greensoftwarelab/Energy-Languages#4]
`.chpl` is the correction extension for Chapel programs. Changing the extensions will enable proper syntax highlighting in GitHub.

**Comment by ben-albrecht** [comment]
I am happy to submit a PR for this change if you'd like.

**Comment by MarcoCouto** [comment]
Hello Ben!

We just downloaded from the CLBG website the source code files, with the same names they had there. Since some benchmark solutions had several versions submitted, changing the extension name was a way of CLBG keeping all versions together without changing the name of the file.

Nevertheless, yes! A pull request for that would be acceptable.
Please take into consideration that, if you go ahead with it, you should also update the corresponding Makefiles, since some of them start with `mv <benchmark>.chapel <benchmark>.chpl`.
